### ISSUE TITLE
Data augmentation on TfRecords for multichannel images

### ISSUE THREAD

**Issue by quartermaine** [tanzhenyu/image_augmentation#2]
I am working with multichannel medical Nifti images which I convert to TfRecords and create a tf.dataset to pass later on a multichannel 3D CNN. The shape of the images is (61,73,61,2) which means the image has 2 channels, does this library support 3D augmentations across all channels?

**Comment by swghosh** [comment]
That doesn't look like a supported use case as of now. But, I hope the code used for image op(s) might be able to handle the augmentation that you're dealing with. You can try the same and feel free to use that code in case it's useful. (I am hoping that my implementation works independently on the last channel so it might just work)

**Comment by swghosh** [comment]
I tried using the image op(s) with 4 rank tensors. Unfortunately, many of the implemented op(s) could not work well with it. 

The following op(s) failed as they heavily depend upon implementations limited to multi-channel 3 rank tensors only.
- Cutout
- Equalize
- Color
- Sharpness
- Contrast

Reasonable restrictions in our implementations would not allow us to modify them in favor of supporting your use case. Also, at this point, it won't be possible to look forward to making such changes. Thanks for your interest in our work.
